### ISSUE TITLE
Two errors report

### ISSUE THREAD

**Issue by cipherchien** [Happyr/StompBundle#1]
Dear Happyr,

I try to implement this bundle into my project, but I got 2 errors:
first error message:  

```
[Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]
  The service "happyr.stomp.broker" has a dependency on a non-existent parameter "happyr.stomp.class".
```

I think the line 11 in services.xml is missing some word "broker_".

second error message:

```
PHP Notice:  Undefined index: broker_uri in /var/....../vendor/happyr/stomp-bundle/HappyR/StompBundle/DependencyInjection/HappyRStompExtension.php on line 25
```

I think the line 24 in Configuration.php is wrong spelling.  It should be "broker_uri", not "borker_uri". 
->scalarNode('borker_uri')->defaultValue('tcp://localhost:61613')->end()

after fix 2 errors, everything will be fine.

**Comment by yuniertilan1** [comment]
I have the next error>   InvalidConfigurationException: Unrecognized options "client_id" under "happy_r_stomp"
